### ISSUE TITLE
CT x should be a finite number

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-integers#100]
```
number-line-integers : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/number-line-integers/number-line-integers_en.html?continuousTest=%7B%22test%22%3A%5B%22number-line-integers%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1606742427416%22%2C%22timestamp%22%3A1606743902507%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: x should be a finite number
Error: Assertion failed: x should be a finite number
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/assert/js/assert.js:25:13)
at ResetAllButton.translate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/scenery/js/nodes/Node.js:2107:17)
at ResetAllButton.setRight (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/scenery/js/nodes/Node.js:2692:12)
at ResetAllButton.set right [as right] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/scenery/js/nodes/Node.js:2696:29)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/scenery/js/nodes/Node.js:5489:23
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/sherpa/lib/lodash-4.17.4.js:9359:14)
at ResetAllButton.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/scenery/js/nodes/Node.js:5476:7)
at new ButtonNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/sun/js/buttons/ButtonNode.js:179:10)
at new RoundButton (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/sun/js/buttons/RoundButton.js:95:5)
id: Bayes Chrome
Snapshot from 11/30/2020, 6:20:27 AM

----------------------------------

number-line-integers : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/number-line-integers/number-line-integers_en.html?continuousTest=%7B%22test%22%3A%5B%22number-line-integers%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1606742427416%22%2C%22timestamp%22%3A1606757230285%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: x should be a finite number
Error: Assertion failed: x should be a finite number
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/assert/js/assert.js:25:13)
at ResetAllButton.translate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/scenery/js/nodes/Node.js:2107:17)
at ResetAllButton.setRight (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/scenery/js/nodes/Node.js:2692:12)
at ResetAllButton.set right [as right] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/scenery/js/nodes/Node.js:2696:29)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/scenery/js/nodes/Node.js:5489:23
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/sherpa/lib/lodash-4.17.4.js:9359:14)
at ResetAllButton.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/scenery/js/nodes/Node.js:5476:7)
at new ButtonNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/sun/js/buttons/ButtonNode.js:179:10)
at new RoundButton (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/sun/js/buttons/RoundButton.js:95:5)
id: Bayes Chrome
Snapshot from 11/30/2020, 6:20:27 AM

----------------------------------

number-line-integers : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/number-line-integers/number-line-integers_en.html?continuousTest=%7B%22test%22%3A%5B%22number-line-integers%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1606742427416%22%2C%22timestamp%22%3A1606753526712%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: x should be a finite number
Error: Assertion failed: x should be a finite number
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/assert/js/assert.js:25:13)
at ResetAllButton.translate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/scenery/js/nodes/Node.js:2107:17)
at ResetAllButton.setRight (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/scenery/js/nodes/Node.js:2692:12)
at ResetAllButton.set right [as right] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/scenery/js/nodes/Node.js:2696:29)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/scenery/js/nodes/Node.js:5489:23
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/sherpa/lib/lodash-4.17.4.js:9359:14)
at ResetAllButton.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/scenery/js/nodes/Node.js:5476:7)
at new ButtonNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/sun/js/buttons/ButtonNode.js:179:10)
at new RoundButton (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/sun/js/buttons/RoundButton.js:95:5)
id: Bayes Chrome
Snapshot from 11/30/2020, 6:20:27 AM

----------------------------------

number-line-integers : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/number-line-integers/number-line-integers_en.html?continuousTest=%7B%22test%22%3A%5B%22number-line-integers%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1606742427416%22%2C%22timestamp%22%3A1606746098429%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: x should be a finite number
Error: Assertion failed: x should be a finite number
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/assert/js/assert.js:25:13)
at ResetAllButton.translate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/scenery/js/nodes/Node.js:2107:17)
at ResetAllButton.setRight (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/scenery/js/nodes/Node.js:2692:12)
at ResetAllButton.set right [as right] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/scenery/js/nodes/Node.js:2696:29)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/scenery/js/nodes/Node.js:5489:23
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/sherpa/lib/lodash-4.17.4.js:9359:14)
at ResetAllButton.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/scenery/js/nodes/Node.js:5476:7)
at new ButtonNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/sun/js/buttons/ButtonNode.js:179:10)
at new RoundButton (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/sun/js/buttons/RoundButton.js:95:5)
id: Bayes Chrome
Snapshot from 11/30/2020, 6:20:27 AM

----------------------------------

number-line-integers : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/number-line-integers/number-line-integers_en.html?continuousTest=%7B%22test%22%3A%5B%22number-line-integers%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1606742427416%22%2C%22timestamp%22%3A1606757379103%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: x should be a finite number
Error: Assertion failed: x should be a finite number
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/assert/js/assert.js:25:13)
at ResetAllButton.translate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/scenery/js/nodes/Node.js:2107:17)
at ResetAllButton.setRight (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/scenery/js/nodes/Node.js:2692:12)
at ResetAllButton.set right [as right] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/scenery/js/nodes/Node.js:2696:29)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/scenery/js/nodes/Node.js:5489:23
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/sherpa/lib/lodash-4.17.4.js:9359:14)
at ResetAllButton.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/scenery/js/nodes/Node.js:5476:7)
at new ButtonNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/sun/js/buttons/ButtonNode.js:179:10)
at new RoundButton (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606742427416/sun/js/buttons/RoundButton.js:95:5)
id: Bayes Chrome
Snapshot from 11/30/2020, 6:20:27 AM
```

**Comment by jbphet** [comment]
This was, I believe, due to a missed push for some work I did on https://github.com/phetsims/number-line-operations/issues/24.  I just did the push and will check CT in an hour or so to make sure the problem has cleared up.

**Comment by jbphet** [comment]
CT has been clear for the last two iterations, closing.
