### ISSUE TITLE
CT Parent already contains child

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-integers#29]
```
number-line-integers : fuzz : require.js : load
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Parent already contains child
Error: Assertion failed: Parent already contains child
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1569243822356/assert/js/assert.js:22:13)
    at BackgroundNode.insertChild (https://bayes.colorado.edu/continuous-testing/snapshot-1569243822356/scenery/js/nodes/Node.js?:585:17)
    at BackgroundNode.addChild (https://bayes.colorado.edu/continuous-testing/snapshot-1569243822356/scenery/js/nodes/Node.js?:628:12)
    at new PointNode (https://bayes.colorado.edu/continuous-testing/snapshot-1569243822356/number-line-integers/js/common/view/NumberLineNode.js?:481:17)
    at handlePointAdded (https://bayes.colorado.edu/continuous-testing/snapshot-1569243822356/number-line-integers/js/common/view/NumberLineNode.js?:260:27)
    at Array.forEach (<anonymous>)
    at ObservableArray.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1569243822356/axon/js/ObservableArray.js?:300:27)
    at new NumberLineNode (https://bayes.colorado.edu/continuous-testing/snapshot-1569243822356/number-line-integers/js/common/view/NumberLineNode.js?:309:33)
    at new SceneView (https://bayes.colorado.edu/continuous-testing/snapshot-1569243822356/number-line-integers/js/scenes/view/SceneView.js?:74:29)
    at new BankSceneView (https://bayes.colorado.edu/continuous-testing/snapshot-1569243822356/number-line-integers/js/scenes/view/BankSceneView.js?:47:7)
id: Bayes Chrome
Approximately 9/23/2019, 7:03:42 AM
number-line-integers : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Parent already contains child
Error: Assertion failed: Parent already contains child
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1569243822356/assert/js/assert.js:22:13)
    at BackgroundNode.insertChild (https://bayes.colorado.edu/continuous-testing/snapshot-1569243822356/scenery/js/nodes/Node.js?:585:17)
    at BackgroundNode.addChild (https://bayes.colorado.edu/continuous-testing/snapshot-1569243822356/scenery/js/nodes/Node.js?:628:12)
    at new PointNode (https://bayes.colorado.edu/continuous-testing/snapshot-1569243822356/number-line-integers/js/common/view/NumberLineNode.js?:481:17)
    at handlePointAdded (https://bayes.colorado.edu/continuous-testing/snapshot-1569243822356/number-line-integers/js/common/view/NumberLineNode.js?:260:27)
    at Array.forEach (<anonymous>)
    at ObservableArray.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1569243822356/axon/js/ObservableArray.js?:300:27)
    at new NumberLineNode (https://bayes.colorado.edu/continuous-testing/snapshot-1569243822356/number-line-integers/js/common/view/NumberLineNode.js?:309:33)
    at new SceneView (https://bayes.colorado.edu/continuous-testing/snapshot-1569243822356/number-line-integers/js/scenes/view/SceneView.js?:74:29)
    at new BankSceneView (https://bayes.colorado.edu/continuous-testing/snapshot-1569243822356/number-line-integers/js/scenes/view/BankSceneView.js?:47:7)
id: Bayes Chrome
Approximately 9/23/2019, 7:03:42 AM
```

**Comment by SaurabhTotey** [comment]
I believe I have fixed this issue. I will wait for a few columns of CT to check though.

**Comment by SaurabhTotey** [comment]
This doesn't appear to show up on CT anymore. Closing.
