### ISSUE TITLE
CT failure: Cannot set property numberLinePoint

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-integers#31]
Continuous testing is currently failing with the error:

```number-line-integers : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot set property numberLinePoint of #<PointController> which has only a getter
TypeError: Cannot set property numberLinePoint of #<PointController> which has only a getter
    at https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/number-line-integers/js/scenes/model/TemperaturePointController.js?:129:32
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/TinyEmitter.js?:59:55)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Property.js?:264:27)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Property.js?:175:16)
    at BooleanProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Property.js?:334:34)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/number-line-integers/js/scenes/model/TemperaturePointController.js?:94:42
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Multilink.js?:41:20)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/TinyEmitter.js?:59:55)
    at Vector2Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Property.js?:264:27)
    at Vector2Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Property.js?:175:16)
id: Bayes Chrome
Approximately 10/1/2019, 9:34:09 AM
number-line-integers : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=false, oldValue=true
Error: Assertion failed: reentry detected, value=false, oldValue=true
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/assert/js/assert.js:22:13)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Property.js?:261:17)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Property.js?:175:16)
    at BooleanProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Property.js?:334:34)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/number-line-integers/js/scenes/model/TemperaturePointController.js?:84:42
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Multilink.js?:41:20)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/TinyEmitter.js?:59:55)
    at Vector2Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Property.js?:264:27)
    at Vector2Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Property.js?:175:16)
    at Vector2Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Property.js?:334:34)
id: Bayes Chrome
Approximately 10/1/2019, 9:34:09 AM
number-line-integers : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught TypeError: Cannot set property numberLinePoint of #<PointController> which has only a getter
TypeError: Cannot set property numberLinePoint of #<PointController> which has only a getter
    at https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/number-line-integers/js/scenes/model/TemperaturePointController.js?:129:32
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/TinyEmitter.js?:59:55)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Property.js?:264:27)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Property.js?:175:16)
    at BooleanProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Property.js?:334:34)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/number-line-integers/js/scenes/model/TemperaturePointController.js?:94:42
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Multilink.js?:41:20)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/TinyEmitter.js?:59:55)
    at Vector2Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Property.js?:264:27)
    at Vector2Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Property.js?:175:16)
id: Bayes Chrome
Approximately 10/1/2019, 9:34:09 AM
number-line-integers : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=false, oldValue=true
Error: Assertion failed: reentry detected, value=false, oldValue=true
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/assert/js/assert.js:22:13)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Property.js?:261:17)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Property.js?:175:16)
    at BooleanProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Property.js?:334:34)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/number-line-integers/js/scenes/model/TemperaturePointController.js?:84:42
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Multilink.js?:41:20)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/TinyEmitter.js?:59:55)
    at Vector2Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Property.js?:264:27)
    at Vector2Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Property.js?:175:16)
    at Vector2Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1569944049663/axon/js/Property.js?:334:34)
id: Bayes Chrome
Approximately 10/1/2019, 9:34:09 AM
```

This looks like it is related to some refactoring that @SaurabhTotey and I were discussing yesterday.

**Comment by jbphet** [comment]
@SaurabhTotey - I commented out the line that was causing the failure, since it looked like it was trying to directly set a single number line point, which is what we're moving away from.  Can you please take a look and delete the line permanently if that's what needs to happen?

**Comment by SaurabhTotey** [comment]
Closing now that NLI is green on CT again.
