### ISSUE TITLE
CT point controller shuld not be put away while controlling a point

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-integers#4]
```
number-line-integers : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: point controller should not be put away while controlling a point
Error: Assertion failed: point controller should not be put away while controlling a point
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1558604509519/assert/js/assert.js:22:13)
    at NLIGenericModel.putPointControllerInBox (https://bayes.colorado.edu/continuous-testing/snapshot-1558604509519/number-line-integers/js/generic/model/NLIGenericModel.js?bust=1558610199299:172:17)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1558604509519/number-line-integers/js/generic/model/NLIGenericModel.js?bust=1558610199299:129:20
    at Array.forEach (<anonymous>)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1558604509519/number-line-integers/js/generic/model/NLIGenericModel.js?bust=1558610199299:125:33
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1558604509519/axon/js/TinyEmitter.js?bust=1558610199299:58:55)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1558604509519/axon/js/Property.js?bust=1558610199299:247:27)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1558604509519/axon/js/Property.js?bust=1558610199299:160:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1558604509519/sun/js/buttons/RadioButtonGroupMember.js?bust=1558610199299:125:16
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1558604509519/axon/js/TinyEmitter.js?bust=1558610199299:58:55)
id: Bayes Chrome
Approximately 5/23/2019, 3:41:49 AM
number-line-integers : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: point controller should not be put away while controlling a point
Error: Assertion failed: point controller should not be put away while controlling a point
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1558604509519/assert/js/assert.js:22:13)
    at NLIGenericModel.putPointControllerInBox (https://bayes.colorado.edu/continuous-testing/snapshot-1558604509519/number-line-integers/js/generic/model/NLIGenericModel.js?bust=1558612752307:172:17)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1558604509519/number-line-integers/js/generic/model/NLIGenericModel.js?bust=1558612752307:129:20
    at Array.forEach (<anonymous>)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1558604509519/number-line-integers/js/generic/model/NLIGenericModel.js?bust=1558612752307:125:33
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1558604509519/axon/js/TinyEmitter.js?bust=1558612752307:58:55)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1558604509519/axon/js/Property.js?bust=1558612752307:247:27)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1558604509519/axon/js/Property.js?bust=1558612752307:160:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1558604509519/sun/js/buttons/RadioButtonGroupMember.js?bust=1558612752307:125:16
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1558604509519/axon/js/TinyEmitter.js?bust=1558612752307:58:55)
id: Bayes Chrome
Approximately 5/23/2019, 3:41:49 AM
```

**Comment by KatieWoe** [comment]
Can't add automated testing label to the issue.  Also, @jbphet this is your sim right?  Its not in the responsible_dev sheet.

**Comment by jbphet** [comment]
This was caused by fuzz test grabbing point controllers that were animating back to the holding box, and I've made this impossible.  CT looks clear, closing.
