### ISSUE TITLE
CT ENOENT: no such file of directory

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-integers#5]
```
number-line-integers : build : phet
Failure to grunt snapshot-1558704687345/number-line-integers:
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (number-line-integers, brands: phet)
Building brand: phet
Fatal error: Perennial task failed:
Error: Error: Error: ENOENT: no such file or directory, open '/data/share/phet/continuous-testing/snapshot-1558704687345/number-line-integers/js/TWIXT/Animation.js'
In module tree:
    number-line-integers-main
      NUMBER_LINE_INTEGERS/generic/NLIGenericScreen
        NUMBER_LINE_INTEGERS/generic/model/NLIGenericModel
          NUMBER_LINE_INTEGERS/common/model/PointController

  at /data/share/phet/continuous-testing/snapshot-1558704687345/chipper/js/grunt/requireBuild.js:107:15
  at /data/share/phet/continuous-testing/snapshot-1558704687345/chipper/node_modules/requirejs/bin/r.js:3059:39
  at /data/share/phet/continuous-testing/snapshot-1558704687345/chipper/node_modules/requirejs/bin/r.js:2999:25
  at Function.prim.nextTick (/data/share/phet/continuous-testing/snapshot-1558704687345/chipper/node_modules/requirejs/bin/r.js:28083:9)
  at Object.errback (/data/share/phet/continuous-testing/snapshot-1558704687345/chipper/node_modules/requirejs/bin/r.js:2998:26)
  at Object.callback (/data/share/phet/continuous-testing/snapshot-1558704687345/chipper/node_modules/requirejs/bin/r.js:2984:23)
  at Object.then (/data/share/phet/continuous-testing/snapshot-1558704687345/chipper/node_modules/requirejs/bin/r.js:3038:23)
  at runBuild (/data/share/phet/continuous-testing/snapshot-1558704687345/chipper/node_modules/requirejs/bin/r.js:30302:48)
  at Object.execCb (/data/share/phet/continuous-testing/snapshot-1558704687345/chipper/node_modules/requirejs/bin/r.js:1946:33)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1558704687345/chipper/node_modules/requirejs/bin/r.js:1133:51)
  at Module.<anonymous> (/data/share/phet/continuous-testing/snapshot-1558704687345/chipper/node_modules/requirejs/bin/r.js:1389:34)
  at /data/share/phet/continuous-testing/snapshot-1558704687345/chipper/node_modules/requirejs/bin/r.js:384:23
  at /data/share/phet/continuous-testing/snapshot-1558704687345/chipper/node_modules/requirejs/bin/r.js:1439:21
  at each (/data/share/phet/continuous-testing/snapshot-1558704687345/chipper/node_modules/requirejs/bin/r.js:309:31)
  at Module.emit (/data/share/phet/continuous-testing/snapshot-1558704687345/chipper/node_modules/requirejs/bin/r.js:1438:17)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1558704687345/chipper/node_modules/requirejs/bin/r.js:1188:30)
  at Module.enable (/data/share/phet/continuous-testing/snapshot-1558704687345/chipper/node_modules/requirejs/bin/r.js:1426:22)
  at Module.init (/data/share/phet/continuous-testing/snapshot-1558704687345/chipper/node_modules/requirejs/bin/r.js:1038:26)
  at Module.<anonymous> (/data/share/phet/continuous-testing/snapshot-1558704687345/chipper/node_modules/requirejs/bin/r.js:1264:30)
  at /data/share/phet/continuous-testing/snapshot-1558704687345/chipper/node_modules/requirejs/bin/r.js:384:23
  at /data/share/phet/continuous-testing/snapshot-1558704687345/chipper/node_modules/requirejs/bin/r.js:2697:17
  at Object.execCb (/data/share/phet/continuous-testing/snapshot-1558704687345/chipper/node_modules/requirejs/bin/r.js:1946:33)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1558704687345/chipper/node_modules/requirejs/bin/r.js:1133:51)
  at Module.enable (/data/share/phet/continuous-testing/snapshot-1558704687345/chipper/node_modules/requirejs/bin/r.js:1426:22)
  at Module.init (/data/share/phet/continuous-testing/snapshot-1558704687345/chipper/node_modules/requirejs/bin/r.js:1038:26)
  at /data/share/phet/continuous-testing/snapshot-1558704687345/chipper/node_modules/requirejs/bin/r.js:1710:36
  at _combinedTickCallback (internal/process/next_tick.js:132:7)
  at process._tickCallback (internal/process/next_tick.js:181:9)

Full Error details:
{}


Approximately 5/24/2019, 7:31:27 AM
```

**Comment by KatieWoe** [comment]
No automated testing label to use.
@jbphet should I be assigning you or @arnabp?

**Comment by jbphet** [comment]
Wow, that's odd.  I had neglected to add the correct library spec and path for TWIXT, but it worked fine until there was a commit related to the cache buster.  Not sure why it **ever** worked without these things, but at any rate, it should be fixed now.  I'll watch CT and close when I'm sure.

**Comment by jbphet** [comment]
CT looks good - closing.
