### ISSUE TITLE
CT issues with media license and point controllers

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-integers#6]
```
number-line-integers : build : phet
Failure to grunt snapshot-1560154672021/number-line-integers:
Running "lint-all" task

Running "report-media" task
>> not-annotated: number-line-integers/images/girl-rock.png
Fatal error: There is an issue with the licenses for media types.


Approximately 6/10/2019, 2:17:52 AM
number-line-integers : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: point controller should not be put away while controlling a point
Error: Assertion failed: point controller should not be put away while controlling a point
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1560154672021/assert/js/assert.js:22:13)
    at ElevationSceneModel.putPointControllerInBox (https://bayes.colorado.edu/continuous-testing/snapshot-1560154672021/number-line-integers/js/scenes/model/NLIScenesModel.js?bust=1560167634394:192:17)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1560154672021/number-line-integers/js/scenes/model/NLIScenesModel.js?bust=1560167634394:211:14
    at Array.forEach (<anonymous>)
    at ElevationSceneModel.reset (https://bayes.colorado.edu/continuous-testing/snapshot-1560154672021/number-line-integers/js/scenes/model/NLIScenesModel.js?bust=1560167634394:210:29)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1560154672021/number-line-integers/js/scenes/model/NLIScenesModel.js?bust=1560167634394:57:20
    at Array.forEach (<anonymous>)
    at NLIScenesModel.reset (https://bayes.colorado.edu/continuous-testing/snapshot-1560154672021/number-line-integers/js/scenes/model/NLIScenesModel.js?bust=1560167634394:56:24)
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1560154672021/number-line-integers/js/scenes/view/NLIScenesScreenView.js?bust=1560167634394:117:17)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1560154672021/axon/js/TinyEmitter.js?bust=1560167634394:59:55)
id: Bayes Chrome
Approximately 6/10/2019, 2:17:52 AM
number-line-integers : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Assertion failed: point controller should not be put away while controlling a point
Error: Assertion failed: point controller should not be put away while controlling a point
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1560154672021/assert/js/assert.js:22:13)
    at ElevationSceneModel.putPointControllerInBox (https://bayes.colorado.edu/continuous-testing/snapshot-1560154672021/number-line-integers/js/scenes/model/NLIScenesModel.js?bust=1560163725053:192:17)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1560154672021/number-line-integers/js/scenes/model/NLIScenesModel.js?bust=1560163725053:211:14
    at Array.forEach (<anonymous>)
    at ElevationSceneModel.reset (https://bayes.colorado.edu/continuous-testing/snapshot-1560154672021/number-line-integers/js/scenes/model/NLIScenesModel.js?bust=1560163725053:210:29)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1560154672021/number-line-integers/js/scenes/model/NLIScenesModel.js?bust=1560163725053:57:20
    at Array.forEach (<anonymous>)
    at NLIScenesModel.reset (https://bayes.colorado.edu/continuous-testing/snapshot-1560154672021/number-line-integers/js/scenes/model/NLIScenesModel.js?bust=1560163725053:56:24)
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1560154672021/number-line-integers/js/scenes/view/NLIScenesScreenView.js?bust=1560163725053:117:17)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1560154672021/axon/js/TinyEmitter.js?bust=1560163725053:59:55)
id: Bayes Chrome
Approximately 6/10/2019, 2:17:52 AM
number-line-integers : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: point controller should not be put away while controlling a point
Error: Assertion failed: point controller should not be put away while controlling a point
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1560154672021/assert/js/assert.js:22:13)
    at ElevationSceneModel.putPointControllerInBox (https://bayes.colorado.edu/continuous-testing/snapshot-1560154672021/number-line-integers/js/scenes/model/NLIScenesModel.js?bust=1560169374219:192:17)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1560154672021/number-line-integers/js/scenes/model/NLIScenesModel.js?bust=1560169374219:211:14
    at Array.forEach (<anonymous>)
    at ElevationSceneModel.reset (https://bayes.colorado.edu/continuous-testing/snapshot-1560154672021/number-line-integers/js/scenes/model/NLIScenesModel.js?bust=1560169374219:210:29)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1560154672021/number-line-integers/js/scenes/model/NLIScenesModel.js?bust=1560169374219:57:20
    at Array.forEach (<anonymous>)
    at NLIScenesModel.reset (https://bayes.colorado.edu/continuous-testing/snapshot-1560154672021/number-line-integers/js/scenes/model/NLIScenesModel.js?bust=1560169374219:56:24)
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1560154672021/number-line-integers/js/scenes/view/NLIScenesScreenView.js?bust=1560169374219:117:17)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1560154672021/axon/js/TinyEmitter.js?bust=1560169374219:59:55)
id: Bayes Chrome
Approximately 6/10/2019, 2:17:52 AM
```

**Comment by KatieWoe** [comment]
No automated testing label, so labeling as bug.

**Comment by jbphet** [comment]
Should be fixed, closing.
